DROP database presupuestos;


CREATE DATABASE  IF NOT EXISTS  `PRESUPUESTOS` DEFAULT CHARACTER  SET UTF8 ;
USE PRESUPUESTOS;

CREATE TABLE IF NOT EXISTS `USUARIOS` (
    ID_USUARIO int AUTO_INCREMENT ,
    NOMBRES VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL 	unique,
    CONTRASEÑA VARCHAR(100),
    SEXO int,
    DUI VARCHAR(11),
    ESTADO enum('1','2','3' ),
    TELEFONO VARCHAR(10) NOT NULL,
    FECHA_CREACION  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO)
)Engine=InnoDB ;

CREATE TABLE IF NOT EXISTS `ROLES`(
ID_ROL int AUTO_INCREMENT,
NOMBRE VARCHAR(15) ,
CONSTRAINT PK_ROLES PRIMARY KEY(ID_ROL)
)Engine=InnoDB;

CREATE TABLE IF NOT EXISTS `SESIONES`(
ID_SESION INT AUTO_INCREMENT,
ID_USUARIO  INT NOT NULL,
FECHA_INICIO_SESION datetime,
FECHA_CIERRE_SESION datetime,
CONSTRAINT PK_SESSIONES PRIMARY KEY(ID_SESION),
CONSTRAINT FK_SESIONES_USUARIOS FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)Engine=InnoDB;



CREATE TABLE IF NOT EXISTS `USUARIOS_ROLES`(
ID_USUARIOS_ROLES INT AUTO_INCREMENT,
ID_ROL INT ,
ID_USUARIO INT ,
CONSTRAINT PK_USUARIO_ROLES PRIMARY KEY(ID_USUARIOS_ROLES),
CONSTRAINT FK_USUARIOS_ROLES_ROL FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL),
CONSTRAINT FK_USUARIOS_ROLES_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)Engine=InnoDB;



CREATE TABLE  IF NOT EXISTS `CATEGORIA`(
ID_CATEGORIA INT AUTO_INCREMENT,
DESCRIPCION VARCHAR (30) NOT NULL,
FECHA_CREACION DATE NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
)Engine=InnoDB;

insert into presupuestos.categoria (DESCRIPCION,FECHA_CREACION ) values('Presupuesto Global','2020-01-02');
insert into presupuestos.categoria (DESCRIPCION,FECHA_CREACION) values('Categoria 1','2020-03-03');
insert into presupuestos.categoria (DESCRIPCION,FECHA_CREACION) values('Categoria 2','2020-04-03');
insert into presupuestos.categoria (DESCRIPCION,FECHA_CREACION) values('Categoria 3','2020-05-04');
insert into presupuestos.categoria (DESCRIPCION,FECHA_CREACION) values('Categoria 4','2020-06-05');


CREATE TABLE  IF NOT EXISTS `PRESUPUESTO`(
ID_PRESUPUESTO INT AUTO_INCREMENT,
ID_CATEGORIA INT  NOT NULL,
MONTO_INICIAL DECIMAL(7,2) NOT NULL, 
MONTO_ACTUAL DECIMAL(7,2) NOT NULL, 
PORCENTAJE_EJECUTADO INT (2), 
ESTADO enum('aprobado','enProceso','denegado' ),
USUARIO_CREA INT NOT NULL,
USUARIO_MODIFICA INT , 
FECHA_CREACION DATE NOT NULL,
FECHA_MODIFICACION DATE ,
CONSTRAINT PK_PRESUPUESTO PRIMARY KEY(ID_PRESUPUESTO),
CONSTRAINT FK_PRESUPUESTOS_USUARIOS FOREIGN KEY(USUARIO_CREA) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT FK_PRESUPUESTOS_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)

)Engine=InnoDB;

#drop table presupuestos.detalle_presupuesto;

CREATE table IF NOT EXISTS `DETALLE_PRESUPUESTO`(
ID_DETALLE_PRESUPUESTO int auto_increment,
ID_PRESUPUESTO int ,
NOMBRE_GASTO varchar(30) , 
UNIDADES INT not null,
MONTO DECIMAL (7,2) NOT NULL,
MONTO_TOTAL DECIMAL (7,2) NOT NULL,
USUARIO_CREA int ,
FECHA_CREACION date not null,
CONSTRAINT PK_DETALE_PRESUPUESTO PRIMARY KEY(ID_DETALLE_PRESUPUESTO),
CONSTRAINT FK_DETALLEPRE_PRESUPUESTO FOREIGN KEY(ID_PRESUPUESTO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
CONSTRAINT FK_DETALLEPRE_USUARIO FOREIGN KEY(USUARIO_CREA) REFERENCES USUARIOS(ID_USUARIO)


)Engine=InnoDb;



USE presupuestos;

	
	
/*
insert into presupuesto (ID_CATEGORIA,MONTO_INICIAL,MONTO_ACTUAL,PORCENTAJE_EJECUTADO,ESTADO,
USUARIO_CREA,FECHA_CREACION) values (3,500,1,20,'aprobado',3,'2020-10-12');

insert into presupuesto (ID_CATEGORIA,MONTO_INICIAL,MONTO_ACTUAL,PORCENTAJE_EJECUTADO,ESTADO,
USUARIO_CREA,FECHA_CREACION) values (4,1500,150,10,'aprobado',3,'2020-10-13');

insert into presupuesto (ID_CATEGORIA,MONTO_INICIAL,MONTO_ACTUAL,PORCENTAJE_EJECUTADO,ESTADO,
USUARIO_CREA,FECHA_CREACION) values (5,3000,300,10,'aprobado',5,'2020-11-14');

*/



CREATE TABLE  IF NOT EXISTS `GASTOS`(
ID_GASTO INT AUTO_INCREMENT,
DESCRIPCION VARCHAR(200) NOT NULL,
UNIDADES INT not null,
MONTO_TOTAL DECIMAL (7,2) NOT NULL,
FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  ,
CONSTRAINT PK_GASTOS PRIMARY KEY(ID_GASTO)
)Engine=InnoDB;


CREATE TABLE  IF NOT EXISTS `TRANSACCIONES`(
ID_TRANSACCION INT AUTO_INCREMENT,
ID_CATEGORIA_DESTINO INT  NOT NULL,
ID_USUARIO INT NOT NULL,
MONTO DECIMAL(7,2) NOT NULL, 
ID_PRESUPUESTO_ORIGEN INT NOT NULL,
ID_PRESUPUESTO_DESTINO INT NOT NULL, 
TIPO enum('aumento','nuevaAsignacion'),
DESCRIPCION VARCHAR(200) NOT NULL, 
FECHA_CREACION DATE NOT NULL,
CONSTRAINT PK_TRANSACCIONES PRIMARY KEY(ID_TRANSACCION),
CONSTRAINT FK_TRANSACCIONES_USUARIOS FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT FK_TRANSACCIONES_CATEGORIA FOREIGN KEY(ID_CATEGORIA_DESTINO) REFERENCES CATEGORIA(ID_CATEGORIA),
CONSTRAINT FK_TRANSACCIONES_PRESUPUESTOS_ORIGEN FOREIGN KEY(ID_PRESUPUESTO_ORIGEN) REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
CONSTRAINT FK_TRANSACCIONES_PRESUPUESTOS_DESTINOS FOREIGN KEY(ID_PRESUPUESTO_DESTINO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO)

)Engine=InnoDB;


insert into  presupuestos.usuarios(nombres,apellidos,email,contraseña,sexo,dui,estado,telefono)
VALUES('Raul ','Perez Martinez','perez@gmail.com','1234',2,'04558819-2',1,'76767677');


insert into  presupuestos.usuarios(nombres,apellidos,email,contraseña,sexo,dui,estado,telefono)
VALUES('Maria Jose','Lazo Mejia','mejia@gmail.com','1234',1,'0228819-2',1,'7000149');

insert into  presupuestos.usuarios(nombres,apellidos,email,contraseña,sexo,dui,estado,telefono)
VALUES('Jonathan','Garca Urrutia','garca@gmail.com','1234',2,'111119-1',1,'7949449');

insert into  presupuestos.usuarios(nombres,apellidos,email,contraseña,sexo,dui,estado,telefono)
VALUES('Samuel ','Murcia Melara','murca@gmail.com','1234',2,'0554819-2',1,'66333123');

insert into  presupuestos.usuarios(nombres,apellidos,email,contraseña,sexo,dui,estado,telefono)
VALUES('Ricargo','Rosa'	,'rosa@gmail.com','1234',2,'15548219-2',1,'783323');



use presupuestos;


insert into roles(nombre)
VALUES('analista presu.');

insert into roles(nombre)
VALUES('administrador');
insert into roles(nombre)
VALUES('jefe presu.');
insert into roles(nombre)
VALUES('tesorero');


INSERT INTO presupuestos.usuarios_roles(id_rol,id_usuario)
  VALUES(2,1);

INSERT INTO presupuestos.usuarios_roles(id_rol,id_usuario)
  VALUES(4,2);

INSERT INTO presupuestos.usuarios_roles(id_rol,id_usuario)
  VALUES(1,3);

INSERT INTO presupuestos.usuarios_roles(id_rol,id_usuario)
  VALUES(3,4);
  
  
INSERT INTO presupuestos.usuarios_roles(id_rol,id_usuario)
  VALUES(1,5);
  
  insert into presupuesto (ID_CATEGORIA,MONTO_INICIAL,MONTO_ACTUAL,PORCENTAJE_EJECUTADO,ESTADO,
	USUARIO_CREA,FECHA_CREACION) values (1,10000,10000,0,'aprobado',3,'2020-10-10');
	
	use presupuestos;
    select *from presupuestos.presupuesto;
    

	insert into presupuesto (ID_CATEGORIA,MONTO_INICIAL,MONTO_ACTUAL,PORCENTAJE_EJECUTADO,ESTADO,
	USUARIO_CREA,FECHA_CREACION) values (2,3000,3000,0,'aprobado',5,'2020-10-12');


  
delete from presupuestos.presupuesto where ID_PRESUPUESTO = '5';

SELECT U.NOMBRES,U.APELLIDOS,R.ID_ROL FROM usuarios as U INNER JOIN usuarios_roles as R 
ON  U.ID_USUARIO= R.ID_USUARIO;


#Just in case someone is having problems with INNER JOINS CLAUSE IN MYSQL,   i found this video and helped me a lot https://www.youtube.com/watch?v=l1Nk8irDJu4
  
  